// svelte/src/lib/Comment.svelte
<script lang="ts">
  export let avatar: string;
  export let author: string;
  export let date: string;
  export let last: boolean = false;
</script>

<div class="media py-4" class:border-bottom={last}>
  <img
    src={avatar}
    class="img-fluid align-self-start rounded-circle mr-3"
    alt="avatar"
    width="61"
    height="61"
    loading="lazy"
  />
  <div class="media-body">
    <h5 class="mt-0">{author}</h5>
    <p>{date}</p>
    <p><slot/></p>
  </div>
</div>

// vue/src/components/Comment.vue
<script setup>


defineProps({
  avatar: {
    type: String,
    required: true
  },
  author: {
    type: String,
    required: true
  },
  date: {
    type: String,
    required: true
  },
  last: {
    type: Boolean,
    required: true
  }
})
</script>
<template>
  <div class="media py-4" :class="last && 'border-bottom'">
    <img :src="avatar" class="img-fluid align-self-start rounded-circle mr-3" alt="avatar" />
    <div class="media-body">
      <h5 class="mt-0">{{author}}</h5>
      <p>{{date}}</p>
      <p><slot></slot></p>
    </div>
  </div>
</template>
