// next/components/Contact/Contact.tsx
import React from 'react'
import Styles from './Contact.module.css';

export const Contact = () => {
  return (
    <section className={`section section-on-footer ${Styles.section}`}>
      <div className="container">
        <div className="row">
          <div className="col-12 text-center">
            <h2 className="section-title">Contact Info</h2>
          </div>
          <div className="col-lg-8 mx-auto">
            <div className="bg-white rounded text-center p-5 shadow-down">
              <h4 className="mb-80">Contact Form</h4>
              <form action="#" className="row">
                <div className="col-md-6">
                  <input type="text" id="name" name="name" placeholder="Full Name" className="form-control px-0 mb-4" required />
                </div>
                <div className="col-md-6">
                  <input type="email" id="email" name="email" placeholder="Email Address" className="form-control px-0 mb-4" required />
                </div>
                <div className="col-12">
                  <textarea name="message" id="message" className="form-control px-0 mb-4" placeholder="Type Message Here" required defaultValue={""} />
                </div>
                <div className="col-lg-6 col-10 mx-auto">
                  <button className="btn btn-primary w-100">send</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

// vue/src/components/Contact.vue
<template>
  <section class="section section-on-footer bg-section">
    <div class="container">
      <div class="row">
        <div class="col-12 text-center">
          <h2 class="section-title">Contact Info</h2>
        </div>
        <div class="col-lg-8 mx-auto">
          <div class="bg-white rounded text-center p-5 shadow-down">
            <h4 class="mb-80">Contact Form</h4>
            <form action="#" class="row">
              <div class="col-md-6">
                <input type="text" id="name" name="name" placeholder="Full Name" class="form-control px-0 mb-4" required>
              </div>
              <div class="col-md-6">
                <input type="email" id="email" name="email" placeholder="Email Address" class="form-control px-0 mb-4" required>
              </div>
              <div class="col-12">
                <textarea name="message" id="message" class="form-control px-0 mb-4"
                  placeholder="Type Message Here" required></textarea>
              </div>
              <div class="col-lg-6 col-10 mx-auto">
                <button class="btn btn-primary w-100">send</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<style scoped>
.bg-section {
  background-image: url('../assets/images/backgrounds/bg-dots.png');
}
</style>
