// vue/src/components/Comments.vue
<script setup>
import PostForm from './PostForm.vue'
import Comment from './Comment.vue';
import { computed } from 'vue';

const props = defineProps({
  list: {
    type: Array,
    required: true
  }
});

const nList = computed(() => {
  return props.list.length
});

const emit = defineEmits(['addComment']);

const sendComment = ( data ) => {
  emit('addComment', data);
}
</script>
<template>
  <section>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <h4 class="font-weight-bold mb-3">Comments {{list.length}}</h4>
          <div class="bg-gray p-5 mb-4">
            <Comment
              v-for="(item, index) in list"
              :keys="index"
              :avatar="item.avatar"
              :author="item.author"
              :date="item.date"
              :last="nList !== (index + 1)"
            >
              {{item.content}}
            </Comment>
          </div>
          <PostForm @onSubmit="sendComment"></PostForm>
        </div>
      </div>
    </div>
  </section>
</template>

// next/components/Comments/Comments.tsx
import React, { FC, useEffect, useState } from 'react'
import { Comment } from './Comment'
import { IComments, IComment } from './Comments.d'

export const Comments: FC<IComments> = ({ list }) => {
  const [items, setItems] = useState<IComment[]>(list)
  const [commentsTotal, setCommentsTotal] = useState(list.length)

  useEffect(() => {
    setCommentsTotal(items.length)
  }, [ items ])

  return (
    <section>
      <div className="container">
        <div className="row">
          <div className="col-lg-12">
            <h4 className="font-weight-bold mb-3">Comments {commentsTotal}</h4>
            <div className="bg-gray p-5 mb-4">
              {
                items.map((item: IComment, index: number) => (
                  <Comment
                    key={`${item.author}-${index}`}
                    id={item.id}
                    avatar={item.avatar}
                    author={item.author}
                    date={item.date}
                    last={commentsTotal !== (index + 1)}
                  >
                    {item.content}
                  </Comment>
                ))
              }
            </div>
            {/* <!-- post form --> */}
          </div>
        </div>
      </div>
    </section>
  )
}
