// svelte/src/routes/portfolio.svelte
<script lang="ts" context="module">
  import type { Load } from '@sveltejs/kit';
  export const prerender = true;

  export const load: Load = async ({ fetch }) => {
    const urls = [
      '/api/clients',
      '/api/portfolio'
    ];
    const promises = urls.map( url => fetch(url) );
    let [clientLogosReq, portfolioReq] = await Promise.all(promises);

    const { logos: clientLogos } = await clientLogosReq.json();
    const { projects, filters } = await portfolioReq.json();

    return {
      props: {
        clientLogos,
        projects,
        filters
      }
    }
  }
</script>

<script lang="ts">
  import Clients from "$lib/Clients.svelte";
  import PageTitle from '$lib/PageTitle.svelte';
  import Portfolio from "$lib/Portfolio.svelte";

  import type { Ilogo } from "$lib/Clients.svelte";
  import type { IProject, IFilter } from "$lib/Portfolio.svelte";

  export let clientLogos: Ilogo[];
  export let projects: IProject[];
  export let filters: IFilter[];
</script>

<svelte:head>
  <title>Portfolio | Kross Creative Template</title>
</svelte:head>

<PageTitle align="center">Portfolio</PageTitle>
<Portfolio projects={projects} title={false} filters={filters}/>
<Clients logos={clientLogos} title/>

// next/pages/portfolio/index.tsx
import React from 'react'
import { GetStaticProps, NextPage } from 'next'

import { PageTitle } from '@components/PageTitle';
import { Clients } from '@components/Clients';
import { Portfolio } from '@components/Portfolio';

import { IPortfolio } from './portfolio.d';
import { portfolio } from '@services/portfolio';
import { clients } from '@services/clients';
import Head from 'next/head';

const PortfolioPage: NextPage<IPortfolio> = ({
  projects,
  filters,
  clientLogos
}) => {
  return (
    <>
      <Head>
        <title>Portfolio | Kross Creative Template</title>
      </Head>
      <PageTitle align="center">Portfolio</PageTitle>
      <Portfolio projects={projects} title={false} filters={filters}/>
      <Clients logos={clientLogos} title/>
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const getPortfolio = await portfolio();
  const { projects, filters } = getPortfolio.data;
  const getClients = await clients();

  return {
    props: {
      clientLogos: getClients.data.logos,
      projects,
      filters
    }
  }
}

export default PortfolioPage
