// svelte/src/lib/Header.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  interface ILink {
    href: string;
    name: string;
  }

  const links: ILink[] = [
    { href: '/', name: 'Home' },
    { href: '/about', name: 'About' },
    { href: '/blog', name: 'Blog' },
    { href: '/portfolio', name: 'Portfolio' },
    { href: '/contact', name: 'Contact' }
  ];

  let menuOpened = false;
  let navBg = false;
  let main: HTMLElement;

  const openMenu = () => {
    if (window.matchMedia("(max-width: 991px)").matches) {
      menuOpened = !menuOpened
    }
  }

  const fnScroll = () => {
    if ( main ) {
      const rect = main.getBoundingClientRect();
      const top = rect.top + window.scrollY;
      navBg = top > 100;
    }
  };

  onMount(() => {
    window.addEventListener('scroll', fnScroll);

    return () => {
      window.removeEventListener('scroll', fnScroll);
    }
  })

</script>

<header class="navigation fixed-top" bind:this={main} id="main-header" class:nav-bg={navBg}>
  <nav class="navbar navbar-expand-lg navbar-dark">
    <a href="/" class="navbar-brand font-tertiary h3">
      <img src="/images/logo.png" alt="Myself" />
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navigation"
      aria-controls="navigation"
      aria-expanded={menuOpened}
      aria-label="Toggle navigation"
      on:click={openMenu}
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse text-center" id="navigation" class:show={menuOpened}>
      <ul class="navbar-nav ml-auto">
        {#each links as link}
          <li class="nav-item">
            <a class="nav-link" href={link.href} on:click={openMenu}>{link.name}</a>
          </li>
        {/each}
      </ul>
    </div>
  </nav>
</header>

// next/components/Header/Header.tsx
import React, { useEffect, useRef, useState } from 'react'
import Image from 'next/image'
import Logo from '@assets/images/logo.png';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { ILink } from './Header.d';

const links: ILink[] = [
  { to: '/', name: 'Home' },
  { to: '/about', name: 'About' },
  { to: '/blog', name: 'Blog' },
  { to: '/portfolio', name: 'Portfolio' },
  { to: '/contact', name: 'Contact' }
];

export const Header = () => {
  const router = useRouter();
  const [menuOpened, setMenuOpened] = useState(false);
  const [navBg, setNavBg] = useState(false);
  const main = useRef<null | HTMLElement>(null);

  const toggleMenu = () => {
    if (window.matchMedia("(max-width: 991px)").matches) {
      setMenuOpened(!menuOpened);
    }
  }

  const fnScroll = () => {
    if ( main ) {
      const rect = (main.current as HTMLElement).getBoundingClientRect();
      const top = rect.top + window.scrollY;
      setNavBg(top > 100);
    }
  };

  useEffect(() => {
    window.addEventListener('scroll', fnScroll);

    return () => {
      window.removeEventListener('scroll', fnScroll)
    }
  }, [])


  return (
    <header className={`navigation fixed-top ${ navBg && 'nav-bg' }`} ref={main}>
      <nav className="navbar navbar-expand-lg navbar-dark">
        <Link href="/">
          <a className="navbar-brand font-tertiary h3">
            <Image src={Logo} alt="Myself" width={77} height={35} />
          </a>
        </Link>
        <button
          className="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navigation"
          aria-controls="navigation"
          aria-expanded={menuOpened}
          aria-label="Toggle navigation"
          onClick={toggleMenu}
        >
          <span className="navbar-toggler-icon" />
        </button>
        <div className={`collapse navbar-collapse text-center ${menuOpened && 'show'}`} id="navigation">
          <ul className="navbar-nav ml-auto">
            {
              links.map( (item: ILink ) => (
                <li className={`nav-item ${ router.pathname === item.to ? 'active' : '' }`} key={item.name}>
                  <Link href={item.to}>
                    <a className="nav-link" onClick={toggleMenu}>{item.name}</a>
                  </Link>
                </li>
              ))
            }
          </ul>
        </div>
      </nav>
    </header>
  )
}
