// next/components/Experience/Experience.tsx
import React, { FC } from 'react'

import { IExperience, Props } from './Experience.d';

import Image from 'next/image';

export const Experience: FC<Props> = ({ list }) => {
  return (
    <section className="section">
      <div className="container">
        <div className="row justify-content-around">
          <div className="col-lg-12 text-center">
            <h2 className="section-title">Experience</h2>
          </div>
          {
            list.map( (experience: IExperience, index: number) => (
              <div className="col-lg-3 col-md-4 text-center" key={`${experience.title}-${index}`}>
                <Image src={experience.icon} alt={experience.title} layout="raw" width={110} height={118}/>
                <p className="mb-0">{experience.period}</p>
                <h4>{experience.title}</h4>
                <h6 className="text-light">{experience.company}</h6>
              </div>
            ))
          }
        </div>
      </div>
    </section>
  )
}

// svelte/src/lib/Experience.svelte
<script lang="ts" context="module">
  export interface IExperience {
    period: string;
    title: string;
    company: string;
    icon: string;
  }
</script>

<script lang="ts">
  export let list: IExperience[]
</script>

<section class="section">
  <div class="container">
    <div class="row justify-content-around">
      <div class="col-lg-12 text-center">
        <h2 class="section-title">Experience</h2>
      </div>
      {#each list as {icon, title, period, company}}
        <div class="col-lg-3 col-md-4 text-center">
          <img src={icon} alt={title} width="110" height="118" loading="lazy"/>
          <p class="mb-0">{period}</p>
          <h4>{title}</h4>
          <h6 class="text-light">{company}</h6>
        </div>
      {/each}
    </div>
  </div>
</section>
