// next/components/Submit/Submit.tsx
import React, { FC } from 'react'
import { ISubmit } from './Submit.d';

export const Submit: FC<ISubmit> = ({children, loading = false}) => {
  return (
    <button
      className="btn btn-primary w-100"
      disabled={loading}
    >
      {
        loading
          ?
            (
              <span
                className="spinner-border spinner-border-md"
                role="status"
                aria-hidden="true">
              </span>
            )
          : children
      }
    </button>
  )
}

// svelte/src/lib/Submit.svelte
<script lang="ts">
  export let loading: boolean = false;
</script>

<button
  class="btn btn-primary w-100"
  disabled={loading}
>
  {#if loading}
    <span
      class="spinner-border spinner-border-md"
      role="status"
      aria-hidden="true">
    </span>
  {:else}
    <slot/>
  {/if}
</button>
