// next/pages/about.tsx
import { AboutDescription } from '@components/AboutDescription'
import { Clients } from '@components/Clients'
import { PageTitle } from '@components/PageTitle'
import { Team } from '@components/Team'
import { WorkProcess } from '@components/WorkProcess'
import React from 'react'

const about = () => {
  return (
    <>
      <PageTitle>About Me</PageTitle>
      <AboutDescription/>
      <WorkProcess/>
      <Team/>
      <Clients title />
    </>
  )
}

export default about;

// vue/src/views/About.vue
<template>
  <PageTitle>About Me</PageTitle>
  <AboutDescription></AboutDescription>
  <WorkProcess></WorkProcess>
  <Team></Team>
  <Clients title></Clients>
</template>
<script>
import PageTitle from '@/components/PageTitle.vue';
import AboutDescription from '@/components/AboutDescription.vue';
import WorkProcess from '@/components/WorkProcess.vue';
import Team from '@/components/Team.vue';
import Clients from '@/components/Clients.vue';

export default {
  components: {
    PageTitle,
    AboutDescription,
    WorkProcess,
    Team,
    Clients
  }
}
</script>
