// svelte/src/routes/about.svelte
<script lang="ts" context="module">
  import type { Load } from '@sveltejs/kit';
  export const prerender = true;

  export const load: Load = async ({ fetch }) => {
    const urls = [
      '/api/clients',
      '/api/workprocess',
      '/api/team'
    ];
    const promises = urls.map( url => fetch(url) );

    let [clientLogosReq, workprocessReq, teamReq] = await Promise.all(promises);

    const { logos: clientLogos } = await clientLogosReq.json();
    const { list: workProcessList } = await workprocessReq.json();
    const { members } = await teamReq.json();

    return {
      props: {
        clientLogos,
        workProcessList,
        members
      }
    }
  }
</script>

<script lang="ts">
  import Clients from "$lib/Clients.svelte";
  import PageTitle from '$lib/PageTitle.svelte';
  import AboutDescription from '$lib/AboutDescription.svelte';
  import WorkProcess from '$lib/WorkProcess.svelte';
  import Team from '$lib/Team.svelte';

  import type { Ilogo } from "$lib/Clients.svelte";
  import type { IProcess } from '$lib/WorkProcess.svelte';
  import type { IMember } from '$lib/Team.svelte';

  export let clientLogos: Ilogo[];
  export let workProcessList: IProcess[];
  export let members: IMember[];
</script>

<svelte:head>
  <title>About | Kross Creative</title>
</svelte:head>

<PageTitle>About Me</PageTitle>
<AboutDescription/>
<WorkProcess list={workProcessList}/>
<Team {members}/>
<Clients logos={clientLogos} title/>

// next/pages/about/index.tsx
import React from 'react'
import { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'

import { AboutDescription } from '@components/AboutDescription'
import { Clients } from '@components/Clients'
import { PageTitle } from '@components/PageTitle'
import { Team } from '@components/Team'
import { WorkProcess } from '@components/WorkProcess'

import { IAbout } from './about'

import { workProcess } from '@services/workProcess'
import { team } from '@services/team'
import { clients } from '@services/clients'

const about: NextPage<IAbout> = ({
  workProcess: workProcessList,
  members,
  clientLogos
}) => {
  return (
    <>
      <Head>
        <title>About | Kross Creative</title>
      </Head>
      <PageTitle>About Me</PageTitle>
      <AboutDescription/>
      <WorkProcess list={workProcessList}/>
      <Team members={members}/>
      <Clients logos={clientLogos} title/>
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const getWorkProcess = await workProcess();
  const getTeam = await team();
  const getClients = await clients();

  return {
    props: {
      workProcess: getWorkProcess.data.list,
      members: getTeam.data.members,
      clientLogos: getClients.data.logos
    }
  }
}

export default about;
